services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eve_healthcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eve_healthcare"]
      interval: 5s
      timeout: 5s
      retries: 5


  redis:
   image: redis:alpine 
   ports:
     - "6379:6379"

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/eve_healthcare?schema=public
      - JWT_SECRET=your_super_secret_jwt_key
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "npx prisma db push && npx tsx src/server.ts"

volumes:
  postgres_data:



  

